'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback } from '@/components/ui/avatar';
import { PageHeader } from '@/components/ui/PageHeader';
import { SentimentBadge } from '@/components/feedback/SentimentBadge';
import {
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  CheckCircle2,
  Download,
  Lightbulb,
  Quote,
  Share2,
} from 'lucide-react';
import { getReportById } from '@/services/reports.service';
import { toast } from 'sonner';
import type { Report } from '@/types';

export default function ReportDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = params.id as string;
  const [report, setReport] = useState<Report | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    (async () => {
      const data = await getReportById(id);
      setReport(data);
      setLoading(false);
    })();
  }, [id]);

  if (loading) {
    return <div className="h-64 animate-pulse rounded-xl bg-slate-200" />;
  }

  if (!report) {
    return (
      <div className="space-y-4">
        <Button variant="ghost" onClick={() => router.push('/reports')}>
          <ArrowLeft className="mr-2 h-4 w-4" /> Back to reports
        </Button>
        <Card>
          <CardContent className="py-12 text-center text-slate-500">
            Report not found.
          </CardContent>
        </Card>
      </div>
    );
  }

  const c = report.contentJson;

  const handleExport = () => {
    toast.success('PDF export ready! Check your downloads.');
  };

  const handleShare = () => {
    if (typeof navigator !== 'undefined' && navigator.clipboard) {
      navigator.clipboard.writeText(typeof window !== 'undefined' ? window.location.href : '');
      toast.success('Link copied to clipboard!');
    }
  };

  return (
    <div className="space-y-6">
      <PageHeader
        title={report.title}
        breadcrumbs={[{ label: 'Reports', href: '/reports' }, { label: report.id }]}
        actions={
          <div className="flex gap-2">
            <Button variant="outline" onClick={handleShare}>
              <Share2 className="mr-2 h-4 w-4" />
              Share
            </Button>
            <Button onClick={handleExport} className="bg-sky-600 hover:bg-sky-700">
              <Download className="mr-2 h-4 w-4" />
              Export
            </Button>
          </div>
        }
      />

      {/* Meta */}
      <div className="flex flex-wrap items-center gap-4 text-sm text-slate-500">
        <span>
          <strong className="text-slate-700">Period:</strong> {report.periodStart} →{' '}
          {report.periodEnd}
        </span>
        <span>•</span>
        <div className="flex items-center gap-2">
          <Avatar className="h-6 w-6">
            <AvatarFallback className="bg-slate-100 text-[10px] font-semibold text-slate-600">
              {report.generatedBy.name
                .split(' ')
                .map((n) => n[0])
                .join('')}
            </AvatarFallback>
          </Avatar>
          <span>Generated by {report.generatedBy.name}</span>
        </div>
        <span>•</span>
        <span>
          {new Date(report.createdAt).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
          })}
        </span>
      </div>

      {/* Executive Summary */}
      <Card>
        <CardHeader>
          <CardTitle className="text-lg">Executive Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <p className="leading-relaxed text-slate-700">{c.summary}</p>
          <div className="mt-4 grid gap-4 sm:grid-cols-2">
            <div className="rounded-lg bg-slate-50 p-4">
              <div className="text-sm text-slate-500">Total Feedback</div>
              <div className="mt-1 text-2xl font-bold text-slate-900">{c.totalFeedback}</div>
            </div>
            <div className="rounded-lg bg-slate-50 p-4">
              <div className="text-sm text-slate-500">New This Week</div>
              <div className="mt-1 text-2xl font-bold text-slate-900">{c.newThisWeek}</div>
            </div>
          </div>
        </CardContent>
      </Card>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Top Themes */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Top Themes</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {c.topThemes.map((theme, i) => (
                <div
                  key={i}
                  className="flex items-center justify-between rounded-lg border border-slate-100 p-3"
                >
                  <div>
                    <div className="font-medium text-slate-900">{theme.name}</div>
                    <div className="text-xs text-slate-500">{theme.count} items</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <SentimentBadge
                      sentiment={
                        theme.sentiment === 'POS'
                          ? 'POS'
                          : theme.sentiment === 'NEG'
                            ? 'NEG'
                            : 'NEU'
                      }
                      showIcon={false}
                    />
                    <span
                      className={`flex items-center gap-0.5 text-xs font-semibold ${
                        theme.change > 0 ? 'text-emerald-600' : 'text-rose-600'
                      }`}
                    >
                      {theme.change > 0 ? (
                        <ArrowUp className="h-3 w-3" />
                      ) : (
                        <ArrowDown className="h-3 w-3" />
                      )}
                      {Math.abs(theme.change)}%
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Sentiment Shift */}
        <Card>
          <CardHeader>
            <CardTitle className="text-lg">Sentiment Shift</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              {[
                { label: 'Positive', current: c.sentimentShift.positive, prev: c.sentimentShift.prevPositive, color: 'bg-emerald-500', textColor: 'text-emerald-600' },
                { label: 'Neutral', current: c.sentimentShift.neutral, prev: c.sentimentShift.prevNeutral, color: 'bg-amber-500', textColor: 'text-amber-600' },
                { label: 'Negative', current: c.sentimentShift.negative, prev: c.sentimentShift.prevNegative, color: 'bg-rose-500', textColor: 'text-rose-600' },
              ].map((s) => {
                const diff = s.current - s.prev;
                return (
                  <div key={s.label}>
                    <div className="flex items-center justify-between text-sm">
                      <span className="font-medium text-slate-700">{s.label}</span>
                      <span className={`flex items-center gap-1 ${s.textColor}`}>
                        {s.current}%
                        <span className="text-xs">
                          ({diff > 0 ? '+' : ''}
                          {diff}pt)
                        </span>
                      </span>
                    </div>
                    <div className="mt-1.5 h-2 overflow-hidden rounded-full bg-slate-100">
                      <div
                        className={`h-full rounded-full ${s.color}`}
                        style={{ width: `${s.current}%` }}
                      />
                    </div>
                    <div className="mt-0.5 text-xs text-slate-400">
                      Previous: {s.prev}%
                    </div>
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Notable Quotes */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Quote className="h-5 w-5 text-sky-600" />
            <CardTitle className="text-lg">Notable Verbatim Quotes</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="grid gap-4 sm:grid-cols-2">
            {c.notableQuotes.map((quote, i) => (
              <div
                key={i}
                className="rounded-lg border border-slate-100 bg-slate-50 p-4"
              >
                <p className="italic text-slate-700">&ldquo;{quote.content}&rdquo;</p>
                <div className="mt-2 flex items-center gap-2">
                  <span className="text-xs text-slate-400">{quote.channel}</span>
                  <SentimentBadge
                    sentiment={quote.sentiment}
                    showIcon={false}
                  />
                </div>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* Recommended Actions */}
      <Card>
        <CardHeader>
          <div className="flex items-center gap-2">
            <Lightbulb className="h-5 w-5 text-amber-500" />
            <CardTitle className="text-lg">Recommended Actions</CardTitle>
          </div>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {c.recommendedActions.map((action, i) => (
              <div key={i} className="flex items-start gap-3">
                <CheckCircle2 className="mt-0.5 h-5 w-5 shrink-0 text-emerald-500" />
                <p className="text-sm text-slate-700">{action}</p>
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
